### ISSUE TITLE
Add code formatting support

### ISSUE THREAD

**Issue by smfrue** [felixbade/open-ai-web-ui#10]
When the answer contains a code snippet add the proper styling around it for readability and easy copy paste.

**Comment by felixbade** [comment]
I like it. I think at least markdown formatting should be easy to render. Not sure how to get the API to return markdown formatted code though. Maybe the brief in the prompt can include a mention about that?

**Comment by felixbade** [comment]
Fixed in 7c3dc5a

**Comment by smfrue** [comment]
You could add a brief after each prompt to separate code and language in a defined format. All in the backend and style it like notion. Just tested it. Works! I'm thrilled! _Put scripts between the two parts [code][/code] and note the used languge between the "" like this: [code language="javascript"]#some code[/code]_
