### ISSUE TITLE
Add a "copy to clipboard" icon to each answer for faster UX

### ISSUE THREAD

**Issue by smfrue** [felixbade/open-ai-web-ui#14]

**Comment by felixbade** [comment]
Which text would be copied? One message or all of them?

**Comment by smfrue** [comment]
Just for one message. if you need the whole message i assume people will screenshot it. IOS supports also full page screenshots for webpages.

**Comment by smfrue** [comment]
Fullpage screenshots apparently just  work directly in safari.

**Comment by felixbade** [comment]
Fixed in 525dabf72790fb, 16c2d25e4f13, and 50f4cc4d508b
