### ISSUE TITLE
Add favicon for better looks on homescreen

### ISSUE THREAD

**Issue by smfrue** [felixbade/open-ai-web-ui#15]
https://www.favicon-generator.org

https://yt3.ggpht.com/a/AATXAJzYT1rumwOdi0mza2hb91s3-7nQVtUSVDEBXQ=s900-c-k-c0xffffffff-no-rj-mo

**Comment by felixbade** [comment]
Absolutely! I think I'll try making something with DALL•E

**Comment by felixbade** [comment]
Fixed in b1e311f56. Technically this is not a favicon, but it works as an app icon.
