### ISSUE TITLE
Change contrast of initial open ai popup

### ISSUE THREAD

**Issue by smfrue** [felixbade/open-ai-web-ui#22]
Imo there is not enough contrast for good readability. Check this [tool](https://coolors.co/contrast-checker/112a46-acc8e5) for good contrast ratio.

**Comment by felixbade** [comment]
Ah, forgot about dark mode. Yes, accessibility facts like contrast are not up for debate.

**Comment by smfrue** [comment]
Ah lol now it makes sense. Was wondering why it looks like this, if it was a design decision or bug.

**Comment by felixbade** [comment]
Improved contrast in both light and dark mode (60e411ce)
